name: Build & Publish

on:
  workflow_dispatch:


permissions:
  contents: read
  actions: write
  id-token: write
  packages: write

jobs:
  build-and-publish:
    name: wasm-pack build & npm publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - name: Cache Cargo registry & build
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Build nodejs
        run: wasm-pack build --target nodejs
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "25"
          registry-url: "https://registry.npmjs.org"
      - name: Publish @pratyay360/upiqrcode
        run: |
          cd pkg
          npm publish  --access public
          